### PR TITLE
Auto-populate GITHUB_TOKEN

### PR DESCRIPTION
**Pull request by joestringer**
If not specified in the environment, run `gh auth token` to fetch a
token in order to fulfill the user's request.

### CODE REVIEW

**Review by aanm — COMMENTED** [review]
Don't we need to specify the token permissions?

**Comment by joestringer** [comment]
```
$ gh auth token --help
This command outputs the authentication token for an account on a given GitHub host.

Without the `--hostname` flag, the default host is chosen.

Without the `--user` flag, the active account for the host is chosen.


USAGE
  gh auth token [flags]

FLAGS
  -h, --hostname string   The hostname of the GitHub instance authenticated with
  -u, --user string       The account to output the token for

INHERITED FLAGS
  --help   Show help for command

LEARN MORE
  Use `gh <command> <subcommand> --help` for more information about a command.
  Read the manual at https://cli.github.com/manual
```

**Comment by joestringer** [comment]
It works, I don't see a way to specify specific permissions :shrug:

**Comment by aanm** [comment]
let's see if it works :crossed_fingers:

**Pull request merged**
